controllers/EmployeesController.php
<?php

namespace app\controllers;

use app\models\EmployeesAttach;
use app\models\EmployeesChildren;
use app\models\EmployeesMove;
use app\models\EmployeesStatus;
use app\models\forms\AttachForm;
use app\models\forms\RoutePerDateForm;
use app\models\RouteAddress;
use Yii;
use app\models\Employees;
use app\models\search\EmployeesSearch;
use yii\base\Security;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use \yii\web\Response;
use yii\helpers\Html;
use yii\web\UploadedFile;

/**
 * EmployeesController implements the CRUD actions for Employees model.
 */
class EmployeesController extends Controller
{

    public function behaviors()
    {
        return [
            'access' => [
                'class' => \yii\filters\AccessControl::className(),

                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
//                        'matchCallback' => function ($rule, $action) {
//                            if (!Yii::$app->user->identity->isSuperAdmin()) {
//                                return $this->redirect(['/']);
//                            }
//                            return true;
//
//                        },
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                    'bulk-delete' => ['post'],
                ],
            ],
        ];
    }

    public function actionIndex()
    {    
        $searchModel = new EmployeesSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionView($id)
    {   
        $request = Yii::$app->request;
        $model = $this->findModel($id);
        $routeModel = new RoutePerDateForm();
        $attachPassport = EmployeesAttach::find()->where(['employees_id'=>$id,'category_file'=>1])->all();
        $attachOther = EmployeesAttach::find()->where(['employees_id'=>$id,'category_file'=>2])->all();
        $children = EmployeesChildren::find()->where(['employees_id'=>$id])->all();
        $statuses = EmployeesStatus::find()->where(['employees_id'=>$id])->all();
            return $this->render('view', [
                'model' => $this->findModel($id),
                'attachPassport' => $attachPassport,
                'attachOther' => $attachOther,
                'routeModel' => $routeModel,
                'children' => $children,
                'statuses' => $statuses,
            ]);
    }

    public function actionCreate()
    {
        $request = Yii::$app->request;
        $model = new Employees();
            if ($model->load($request->post()) && $model->save()) {
                $model->main_photo = UploadedFile::getInstance($model, 'main_photo');
                $main_path = "images/photo/";
                if (!empty($model->main_photo)) {
                    if (!file_exists(($main_path))) {
                        mkdir($main_path, 0777, true);
                    }
                    $main_photo = $main_path . time() . Yii::$app->security->generateRandomString(5) . '.' . $model->main_photo->extension;
                    $model->main_photo->saveAs($main_photo);
                    $model->foto = '/'.$main_photo;
                    $model->save();
                }
                //загрузка паспортов .
                $model->saveAttachPassport();
                //загрузка других .
                $model->saveAttachOther();
                //Сохранить список детей
                $model->children = $request->post('Employees')['children'];
                $model->saveChildren();
                return $this->redirect(['index', 'id' => $model->id]);
            } else {
                return $this->render('create', [
                    'model' => $model,
                ]);
            }

    }

    public function actionUpdate($id)
    {
        $request = Yii::$app->request;
        $model = $this->findModel($id);
        $queryPassport = EmployeesAttach::find()->where(['employees_id'=>$id,'category_file'=>1]);
        $dataProviderPassport = new ActiveDataProvider(['query' => $queryPassport]);
        $queryOther = EmployeesAttach::find()->where(['employees_id'=>$id,'category_file'=>2]);
        $dataProviderOther = new ActiveDataProvider(['query' => $queryOther]);
        $model->children = EmployeesChildren::find()->where(['employees_id'=>$id])->asArray()->all();

        if ($model->load($request->post()) && $model->save()) {
            $model->main_photo = UploadedFile::getInstance($model, 'main_photo');
            $main_path = "images/photo/";
            if (!empty($model->main_photo)) {
                if (!file_exists(($main_path))) {
                    mkdir($main_path, 0777, true);
                }
                $main_photo = $main_path . time() . Yii::$app->security->generateRandomString(5) . '.' . $model->main_photo->extension;
                $model->main_photo->saveAs($main_photo);
                $model->foto = '/'.$main_photo;
                $model->save();
            }

            //загрузка паспортов .
            $model->saveAttachPassport();
            //загрузка других .
            $model->saveAttachOther();
            //Сохранить список детей
            $model->children = $request->post('Employees')['children'];
            $model->saveChildren();

            return $this->redirect(['index']);
        } else {
            return $this->render('update', [
                'model' => $model,
                'dataProviderPassport' => $dataProviderPassport,
                'dataProviderOther' => $dataProviderOther,

            ]);
            }
    }

    public function actionDelete($id)
    {
        $request = Yii::$app->request;
        $this->findModel($id)->delete();

        if($request->isAjax){
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ['forceClose'=>true,'forceReload'=>'#crud-datatable-pjax'];
        }else{
            return $this->redirect(['index']);
        }


    }

    public function actionAttachDelete($category, $id)
    {
        $request = Yii::$app->request;
        EmployeesAttach::findOne($id)->delete();
        if($request->isAjax){
            Yii::$app->response->format = Response::FORMAT_JSON;
            if ($category ==1) {
                return ['forceClose'=>true,'forceReload'=>'#crud-datatable-passport-pjax'];
            } else {
                return ['forceClose'=>true,'forceReload'=>'#crud-datatable-other-pjax'];
            }

        }else{
            return $this->redirect(['index']);
        }


    }

    public function actionAttachAdd($category,$id)
    {
        $request = Yii::$app->request;
        $model = new AttachForm();
        if ($request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            if ($request->isGet) {
                return [
                    'title' => "Добавить вложения",
                    'content' => $this->renderAjax('_form-attach', [
                        'model' => $model,
                    ]),
                    'footer' => Html::button('Закрыть', ['class' => 'btn btn-primary pull-left', 'data-dismiss' => "modal"]) .
                        Html::button('Сохранить', ['class' => 'btn btn-info', 'type' => "submit"])
                ];
            }else if($model->load($request->post())){
                $model->saveAttach($category,$id);
                if ($category ==1) {
                    return ['forceClose'=>true,'forceReload'=>'#crud-datatable-passport-pjax'];
                } else {
                    return ['forceClose'=>true,'forceReload'=>'#crud-datatable-other-pjax'];
                }
            }else{
                return [
                    'title' => "Добавить вложения",
                    'content' => $this->renderAjax('_form-attach', [
                        'model' => $model,
                    ]),
                    'footer' => Html::button('Закрыть', ['class' => 'btn btn-primary pull-left', 'data-dismiss' => "modal"]) .
                        Html::button('Сохранить', ['class' => 'btn btn-info', 'type' => "submit"])
                ];
            }
        }else{
            if ($model->load($request->post()) && $model->save()) {
                return $this->redirect(['update', 'id' => $model->id]);
            } else {
                return $this->render('_form-attach', [
                    'model' => $model,
                ]);
            }
        }
    }

    public function actionBulkDelete()
    {        
        $request = Yii::$app->request;
        $pks = explode(',', $request->post( 'pks' )); // Array or selected records primary keys
        foreach ( $pks as $pk ) {
            $model = $this->findModel($pk);
            $model->delete();
        }

        if($request->isAjax){
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ['forceClose'=>true,'forceReload'=>'#crud-datatable-pjax'];
        }else{
            /*
            *   Process for non-ajax request
            */
            return $this->redirect(['index']);
        }
       
    }

    public function actionGetMoveRoute()
    {
        $request = Yii::$app->request;
        //if($request->isAjax) {

views/employees/_columns-attach.php
<?php

use app\helpers\StatusHelper;
use app\models\Employees;
use yii\helpers\Url;

return [
    [
        'class' => 'kartik\grid\CheckboxColumn',
        'width' => '20px',
    ],
    [
        'class' => 'kartik\grid\SerialColumn',
        'width' => '30px',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'file',
    ],


    [
        'class' => 'kartik\grid\ActionColumn',
        'header' =>"&nbsp&nbsp&nbspДействия&nbsp&nbsp&nbsp",
        'dropdown' => false,
        'vAlign'=>'middle',
        'urlCreator' => function($action, $model, $key, $index) { 
                return Url::to([$action,'id'=>$key]);
        },
        'viewOptions'=>['label'=>'<button class="btn btn-info btn-xs"><span class="glyphicon glyphicon-eye-open"></span></button>','role'=>'modal-remote'],
        'updateOptions'=>['label'=>'<button class="btn btn-warning btn-xs"><span class="glyphicon glyphicon-pencil"></span></button>','data-pjax'=>0,'title'=>'Изменить', 'data-toggle'=>'tooltip'],
        'deleteOptions'=>['role'=>'modal-remote','title'=>'Удалить',
            'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
            'data-request-method'=>'post',
            'label'=>'<button class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-trash"></span></button>',
            'data-toggle'=>'tooltip',
            'data-confirm-title'=>'Вы уверенны?',
            'data-confirm-message'=>'Вы действительно хотите удалить запись '],
],

];   

views/employees/_form-attach.php
<?php

use kartik\widgets\FileInput;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Employees */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="employees-form-attach">

    <?php $form = ActiveForm::begin([
        'options' => [
            'method' => 'post',
            'enctype' => 'multipart/form-data',
            ]
    ]); ?>
    <?=$form->field($model, 'files[]')->widget(FileInput::classname(), [
        'options'=>[
            'multiple'=>true,
        ],
        'pluginOptions' => [
            //'hideThumbnailContent'=> true,
            'overwriteInitial'=>true,
            'showUpload' => false,
            'browseLabel' => '',
            'maxFileSize'=>2800,
            //'theme' => "explorer",
        ]
    ])->label(false);?>
    <?php ActiveForm::end(); ?>
    
</div>

views/employees/_form-create.php
<?php

use app\models\Employees;
use app\models\EmployeesCategory;
use app\models\EmployeesPosition;
use kartik\date\DatePicker;
use kartik\widgets\FileInput;
use kartik\widgets\Select2;
use unclead\multipleinput\MultipleInput;
use unclead\multipleinput\MultipleInputColumn;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Employees */
/* @var $form yii\widgets\ActiveForm */
?>

<style>
    .modal-lg {
        width: 1200px;
    }
    .form-group {
        margin-bottom: 0px;
    }
    samp {
        display: none;
    }
    .file-thumbnail-footer {
        display: none;
    }
    .form-group-sm .form-control {
        height: 27px;
    }
    .form-group-sm select.form-control {
        height: 27px;
    }

    .help-block {
        margin: 0px;
    }
    label {
        font-size: 12px;
        margin-bottom: 0px;
    }
    .file-drop-zone-title {
        padding: 55px 10px;
    }
    .input-group-addon {
        padding: 0px 6px;
    }

</style>
<div class="employees-form">

    <?php $form = ActiveForm::begin([
        'options' => [
            'method' => 'post',
            'enctype' => 'multipart/form-data',
            ]
    ]); ?>
    <div class="row">
        <div class="form-group">
            <?= Html::a( 'Отмена', \yii\helpers\Url::to(['/employees/index']), ['class' => 'btn btn-danger pull-right']) ?>
            <?= Html::submitButton('Создать', ['class' => 'btn btn-primary  pull-right']) ?>

        </div>
    </div>

    <div class="row">
        <div class="col-md-8 bg-info">
            <h5>Персональные данные</h5>
        </div>
        <div class="col-md-4 bg-info">
            <h5>Паспортные данные</h5>
        </div>

    </div>
    <div class="row form-group form-group-sm">
        <div class="col-md-4">
            <?= $form->field($model, 'status')->dropDownList(Employees::getStatuses()) ?>
            <?= $form->field($model, 'position_id')->dropDownList(EmployeesPosition::getPositionList())?>
            <?= $form->field($model, 'lastname')->textInput(['maxlength' => true]) ?>
            <?= $form->field($model, 'firstname')->textInput(['maxlength' => true]) ?>
            <?= $form->field($model, 'parentname')->textInput(['maxlength' => true]) ?>
            <?= $form->field($model, 'birthday')->widget(DatePicker::classname(), [
                'type' => DatePicker::TYPE_COMPONENT_APPEND,
                'pickerIcon' => '<i class="glyphicon glyphicon-calendar text-primary"></i>',
                'removeIcon' => '<i class="glyphicon glyphicon-trash text-danger"></i>',
                'pluginOptions' => [
                    'autoclose'=>true,
                    'format' => 'yyyy-mm-dd',
                ]
            ]); ?>
            <?= $form->field($model, 'family_status')->dropDownList(Employees::getFamilyStatuses()) ?>
            <?= $form->field($model, 'children')->widget(MultipleInput::className(), [
                'columns' => [
                    [
                        'name'  => 'name',
                        'title' => 'Имя ребенка',
                    ],
                    [
                        'name'  => 'birthday',
                        'type'  => \kartik\date\DatePicker::className(),
                        'title' => 'День рождения',
                        'options' => [
                            'type' => DatePicker::TYPE_COMPONENT_APPEND,
                            'pickerIcon' => '<i class="glyphicon glyphicon-calendar text-primary"></i>',
                            'removeIcon' => '<i class="glyphicon glyphicon-trash text-danger"></i>',
                            'pluginOptions' => [
                                'autoclose'=>true,
                                'format' => 'yyyy-mm-dd',
                            ]
                        ]
                    ],
                    [
                        'name'  => 'sex',
                        'type'  => 'dropDownList',
                        'title' => 'Пол',
                        'defaultValue' => 1,
                        'items' => [
                            1 => 'Мужской',
                            2 => 'Женский'
                        ]
                    ],

                ],
                'min'               => 0, // should be at least 2 rows
                'allowEmptyList'    => false,
                'enableGuessTitle'  => true,
                'addButtonPosition' => MultipleInput::POS_HEADER, // show add button in the header
            ])->label(false);?>
        </div>
        <div class="col-md-4">
            <?= $form->field($model, 'address')->textarea(['rows'=>2, 'maxlength' => true]) ?>
            <?= $form->field($model, 'phone')->textInput(['maxlength' => true]) ?>
            <?= $form->field($model, 'phone_add')->textInput(['maxlength' => true]) ?>
            <?= $form->field($model, 'phone_guarantor')->textInput(['maxlength' => true]) ?>
            <?= $form->field($model, 'FIO_guarantor')->textInput(['maxlength' => true]) ?>
            <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>
            <?= $form->field($model, 'phone_model')->textInput(['maxlength' => true]) ?>
            <?= $form->field($model, 'phone_id')->textInput(['maxlength' => true]) ?>

        </div>
        <div class="col-md-4">

            <?= $form->field($model, 'start_work')->widget(DatePicker::classname(), [
                'type' => DatePicker::TYPE_COMPONENT_APPEND,
                'pickerIcon' => '<i class="glyphicon glyphicon-calendar text-primary"></i>',
                'removeIcon' => '<i class="glyphicon glyphicon-trash text-danger"></i>',
                'pluginOptions' => [
                    'autoclose'=>true,
                    'format' => 'yyyy-mm-dd'
                ]
            ]); ?>
            <?= $form->field($model, 'pasport_number')->textInput(['maxlength' => true]) ?>
            <?= $form->field($model, 'pasport_publish')->textInput(['maxlength' => true]) ?>
            <?= $form->field($model, 'pasport_date')->widget(DatePicker::classname(), [
                'type' => DatePicker::TYPE_COMPONENT_APPEND,
                'pickerIcon' => '<i class="glyphicon glyphicon-calendar text-primary"></i>',
                'removeIcon' => '<i class="glyphicon glyphicon-trash text-danger"></i>',
                'pluginOptions' => [
                    'autoclose'=>true,
                    'format' => 'yyyy-mm-dd'
                ]
            ]); ?>
            <?= $form->field($model, 'code_structure')->textInput(['maxlength' => true]) ?>
            <?= $form->field($model, 'specializations')->widget(select2::classname(), [
                'data' => Employees::$specializationList,
                'options' => [
                    'placeholder' => 'Выберите специализации ...',
                    'multiple' => true
                ],
            ]); ?>
            <?= $form->field($model, 'other_data')->textarea(['rows'=>2, 'maxlength' => true]) ?>

        </div>
    </div>
    <div class="row">
        <div class="col-md-4 bg-info">
            <h5>Фото </h5>
        </div>
        <div class="col-md-4 bg-info">
            <h5>Сканы паспорта</h5>
        </div>
        <div class="col-md-4 bg-info">
            <h5>Прочие файлы</h5>
        </div>

    </div>
<div class="row">
    <div class="col-md-4">
        <?= $form->field($model, 'main_photo')->widget(FileInput::classname(), [
            'options'=>[
                'multiple'=>false,
                'accept' => 'image/*',
            ],
            'pluginOptions' => [
                'overwriteInitial'=>true,
                'showUpload' => false,
                'browseLabel' => '',
                'removeLabel' => '',
                'maxFileSize'=>2800,

            ]
        ])->label(false);?>
    </div>
    <div class="col-md-4">
        <?= $form->field($model, 'pasport_files[]')->widget(FileInput::classname(), [
            'options'=>[
                'multiple'=>true,
            ],
            'pluginOptions' => [
                'hideThumbnailContent'=> true,
                'overwriteInitial'=>true,
                'showUpload' => false,
                'browseLabel' => '',
                'maxFileSize'=>2800,
                'theme' => "explorer",
            ]
        ])->label(false);?>
    </div>
    <div class="col-md-4 ">
        <?= $form->field($model, 'other_files[]')->widget(FileInput::classname(), [
            'options'=>[
                'multiple'=>true,
            ],
            'pluginOptions' => [
                'hideThumbnailContent'=> true,
                'overwriteInitial'=>true,
                'showUpload' => false,
                'browseLabel' => '',
                'maxFileSize'=>2800,
                'theme' => "explorer",
            ]
        ])->label(false); ?>
    </div>

</div>
    <?php ActiveForm::end(); ?>
    
</div>

views/employees/_form-update.php
<?php



/* @var $this yii\web\View */
/* @var $model app\models\Employees */
/* @var $form yii\widgets\ActiveForm */
?>

<style>
    .modal-lg {
        width: 1200px;
    }
    .form-group {
        margin-bottom: 0px;
    }
    samp {
        display: none;
    }
    .file-thumbnail-footer {
        display: none;
    }
    .form-group-sm .form-control {
        height: 25px;
    }
    .form-group-sm select.form-control {
        height: 25px;
    }

    .help-block {
        margin: 0px;
    }
    label {
        font-size: 12px;
        margin-bottom: 0px;
    }
    .file-drop-zone-title {
        padding: 55px 10px;
    }
    .input-group-addon {
        padding: 0px 6px;
    }

</style>
<div class="employees-form">

    <?php $form = ActiveForm::begin([
        'options' => [
            'method' => 'post',
            'enctype' => 'multipart/form-data',
            ]
    ]); ?>
    <div class="row">
        <div class="form-group">
            <?= Html::a( 'Отмена', \yii\helpers\Url::to(['/employees/index']), ['class' => 'btn btn-danger pull-right']) ?>
            <?= Html::submitButton('Создать', ['class' => 'btn btn-primary  pull-right']) ?>

        </div>
    </div>

    <div class="row">
        <div class="col-md-8 bg-info">
            <h5>Персональные данные</h5>
        </div>
        <div class="col-md-4 bg-info">
            <h5>Паспортные данные</h5>
        </div>

    </div>
    <div class="row form-group form-group-sm">
        <div class="col-md-4">
            <?= $form->field($model, 'status')->dropDownList(Employees::getStatuses()) ?>
            <?= $form->field($model, 'category_id')->dropDownList(EmployeesCategory::getCategoryList()) ?>
            <?= $form->field($model, 'lastname')->textInput(['maxlength' => true]) ?>
            <?= $form->field($model, 'firstname')->textInput(['maxlength' => true]) ?>
            <?= $form->field($model, 'parentname')->textInput(['maxlength' => true]) ?>
            <?= $form->field($model, 'birthday')->widget(DatePicker::classname(), [
                'type' => DatePicker::TYPE_COMPONENT_APPEND,
                'pickerIcon' => '<i class="glyphicon glyphicon-calendar text-primary"></i>',
                'removeIcon' => '<i class="glyphicon glyphicon-trash text-danger"></i>',
                'pluginOptions' => [
                    'autoclose'=>true,
                    'format' => 'yyyy-mm-dd',
                ]
            ]); ?>
            <?= $form->field($model, 'address')->textarea(['rows'=>2, 'maxlength' => true]) ?>
        </div>
        <div class="col-md-4">
            <?= $form->field($model, 'family_status')->dropDownList(Employees::getFamilyStatuses()) ?>
            <?= $form->field($model, 'phone')->textInput(['maxlength' => true]) ?>
            <?= $form->field($model, 'phone2')->textInput(['maxlength' => true]) ?>
            <?= $form->field($model, 'position_id')->dropDownList(EmployeesPosition::getPositionList())?>
            <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>
            <?= $form->field($model, 'camera')->checkbox() ?>
            <?= $form->field($model, 'internet')->checkbox() ?>
            <?= $form->field($model, 'office')->checkbox() ?>
            <?= $form->field($model, 'departure_area')->checkbox() ?>
        </div>
        <div class="col-md-4">
            <?= $form->field($model, 'prefers_work')->textInput() ?>
            <?= $form->field($model, 'start_work')->widget(DatePicker::classname(), [
                'type' => DatePicker::TYPE_COMPONENT_APPEND,
                'pickerIcon' => '<i class="glyphicon glyphicon-calendar text-primary"></i>',
                'removeIcon' => '<i class="glyphicon glyphicon-trash text-danger"></i>',
                'pluginOptions' => [
                    'autoclose'=>true,
                    'format' => 'yyyy-mm-dd'
                ]
            ]); ?>
            <?= $form->field($model, 'pasport_number')->textInput(['maxlength' => true]) ?>
            <?= $form->field($model, 'pasport_publish')->textInput(['maxlength' => true]) ?>
            <?= $form->field($model, 'pasport_date')->widget(DatePicker::classname(), [
                'type' => DatePicker::TYPE_COMPONENT_APPEND,
                'pickerIcon' => '<i class="glyphicon glyphicon-calendar text-primary"></i>',
                'removeIcon' => '<i class="glyphicon glyphicon-trash text-danger"></i>',
                'pluginOptions' => [
                    'autoclose'=>true,
                    'format' => 'yyyy-mm-dd'
                ]
            ]); ?>
            <?= $form->field($model, 'code_structure')->textInput(['maxlength' => true]) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4 bg-info">
            <h5>Фото </h5>
        </div>
        <div class="col-md-4 bg-info">
            <h5>Сканы паспорта</h5>
        </div>
        <div class="col-md-4 bg-info">
            <h5>Прочие файлы</h5>
        </div>

    </div>
<div class="row">

    <div class="col-md-4">
        <?= $form->field($model, 'main_photo')->widget(FileInput::classname(), [
            'options'=>[
                'multiple'=>false,
                'accept' => 'image/*',
            ],
            'pluginOptions' => [
                'overwriteInitial'=>true,
                'showUpload' => false,
                'browseLabel' => '',
                'removeLabel' => '',
                'maxFileSize'=>2800,
                'initialPreview' => [
                        "<img src='" . $model->foto . "' class='kv-file-content additional_photos file-preview-image'>"
                ],
            ]
        ])->label(false);?>
    </div>
    <div class="col-md-4">
        <?=GridView::widget([
            'id'=>'crud-datatable-passport',
            'dataProvider' => $dataProviderPassport,
            //'filterModel' => $searchModel,
            'pjax'=>true,
            'columns' => [
                    [
                        'class'=>'\kartik\grid\DataColumn',
                        'attribute'=>'file',
                    ],
                [
                    'class' => 'kartik\grid\ActionColumn',
                    'header' =>"",
                    'template' => '{delete}',
                    'dropdown' => false,
                    'vAlign'=>'middle',
                    'urlCreator' => function($action, $model, $key, $index) {
                        return Url::to(['passport-attach-delete','id'=>$key]);
                    },
                    'deleteOptions'=>['role'=>'modal-remote','title'=>'Удалить',
                        'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
                        'data-request-method'=>'post',
                        'label'=>'<button class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-trash"></span></button>',
                        'data-toggle'=>'tooltip',
                        'data-confirm-title'=>'Вы уверенны?',
                        'data-confirm-message'=>'Вы действительно хотите удалить запись '],
                ],
                ],
            'toolbar'=> [
                ['content'=>''

                ],
            ],
            'striped' => true,
            'condensed' => true,
            'responsive' => true,
            'panel' => [
                'heading' => false,
                'footer' => false,
                'before' => false,
                'after'=>'<div style="margin-top:10px;">' .
                    Html::a('Добавить <i class="glyphicon glyphicon-plus"></i>', ['eployees/foto-add'],
                        ['role'=>'modal-remote','title'=> 'Добавить', 'class'=>'btn btn-info']).
                    '</div>',
            ]
        ])?>
    </div>
    <div class="col-md-4 ">
        <?= $form->field($model, 'other_files[]')->widget(FileInput::classname(), [
            'options'=>[
                'multiple'=>true,
            ],
            'pluginOptions' => [
                'hideThumbnailContent'=> true,
                'overwriteInitial'=>true,
                'showUpload' => false,
                'browseLabel' => '',
                'maxFileSize'=>2800,
                'theme' => "explorer",
            ]
        ])->label(false); ?>
    </div>

</div>
    <?php ActiveForm::end(); ?>
    
</div>

views/employees/_view_status.php
<?php

use app\helpers\StatusHelper;
use app\models\Employees;
use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Employees */
?>
<style>


</style>
<div class="employees-view">

    <?php foreach ($statuses as $status) :?>
        <div class="row oglavl">
            <div class="col-md-6">
                <span class="emp-label"><?=Yii::$app->formatter->asDate($status->date_status,'dd.MM.yyyy')?></span>
                <span class="emp-value"><?=Employees::getStatuses()[$status->status]?></span>
            </div>
        </div>
    <?php endforeach;?>


</div>

views/employees/add-attach.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Employees */

?>
<div class="employees-create">
    <?= $this->render('_form-attach', [
        'model' => $model,
    ]) ?>
</div>

views/employees/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Employees */

?>
<div class="employees-create">
    <?= $this->render('_form-create', [
        'model' => $model,
    ]) ?>
</div>