models/Projects.php
<?php

namespace app\models;

use app\models\search\ProjectsPlacementSearch;
use Yii;

/**
 * This is the model class for table "projects".
 *
 * @property int $id
 * @property string $name Название
 * @property int $client_id Заказчик
 * @property string $date_start Дата начала
 * @property string $date_end Дата окончания
 *
 * @property int $daysDuration
 *
 * @property Clients $client
 * @property float $project_cost
 * @property ProjectsPlacement[] $projectsPlacements
 * @property Routes[] $routes
 */
class Projects extends \yii\db\ActiveRecord
{
    /**
     * @var string
     */
    public $intervalDates;

    public $placements;

    public $maketFile;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'projects';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['client_id','normal_one'], 'integer'],
            [['name','maket'], 'string', 'max' => 255],
            [['client_id'], 'exist', 'skipOnError' => true, 'targetClass' => Clients::className(), 'targetAttribute' => ['client_id' => 'id']],
            [['route_template_id'], 'exist', 'skipOnError' => true, 'targetClass' => RouteTemplates::className(), 'targetAttribute' => ['route_template_id' => 'id']],
            [['intervalDates','info_add','maket_file','date_start','date_end'], 'safe'],
            //[['maketFile'], 'file', 'skipOnEmpty' => false],
        ];
    }

    /**
     * {@inheritdoc}
     */

    public function afterFind()
    {
        parent::afterFind(); // TODO: Change the autogenerated stub



    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Проeкт',
            'client_id' => 'Заказчик',
            'project_cost' => 'Общая сумма',
            'date_start' => 'Дата начала',
            'date_end' => 'Дата окончания',
            'intervalDates' => 'Дата начала — Дата завершения',
            'normal_one' => 'Норма на одного промоутера',
            'maket' => 'Макет',
            'maket_file' => 'Файл макета',
            'info_add' => 'Доплнительная информация',
            'route_template_id' => 'Шаблон маршрутного листа',

        ];
    }

    /**
     * Получить длительность выполнения в днях
     * @return int
     */
    public function getDaysDuration()
    {
        $startTimestamp = strtotime($this->date_start);
        $endTimestamp = strtotime($this->date_end);

        return round(($endTimestamp - $startTimestamp) / 86400);
    }

    /**
     * Получить длительность выполнения в днях
     * @return int
     */
    public function getDaysDurationPeriod($start,$end)
    {
        $startTimestamp = strtotime($start);
        $endTimestamp = strtotime($end);

        return round(($endTimestamp - $startTimestamp) / 86400);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getClient()
    {
        return $this->hasOne(Clients::class, ['id' => 'client_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProjectsPlacements()
    {
        return $this->hasMany(ProjectsPlacement::className(), ['project_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRoutes()
    {
        return $this->hasMany(Routes::className(), ['project_id' => 'id']);
    }


    public function getRouteTemplates()
    {
        return $this->hasOne(RouteTemplates::className(), ['id' => 'route_template_id']);
    }

    public function savePlacements($id = null)
    {
        if ($id) {
            $model=ProjectsPlacement::find()->where(['id'=>$id])->one();
            if (!$model) {
                $model = new ProjectsPlacement();
            }
        } else {
            $model = new ProjectsPlacement();
        }
        $prices = Prices::find()->indexBy('id')->all();
        $all_cost = 0;
        $model->project_id = $this->id;
        $model->placement_id = $this->placements->placement_id;
        $model->price_id = $this->placements->price_id;
        $model->price = $prices[$this->placements->price_id]->price;
        $model->circulation = $this->placements->circulation;
        $all_cost +=  $model->price * $this->placements->circulation;
        $model->save();
        //$this->project_cost = $all_cost;
        //$this->save();
    }

    public function beforeDelete()
    {
        $routes = Routes::find()->where(['project_id'=>$this->id])->all();
        foreach ($routes as $route) {
            $route->delete();
        }
        $prjectPlacement = ProjectsPlacement::deleteAll(['project_id'=>$this->id]);
        $projectAddress = ProjectAddress::deleteAll(['project_id'=>$this->id]);
        $zones = Zones::deleteAll(['project_id'=>$this->id]);
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    /**
     *
     */
    public function getAllAddresses()
    {
        $addresses = [];

        foreach($this->routes as $route) {
            $adrs = $route->addressLists;
            $addresses = array_merge($addresses, $adrs);
        }

        return $addresses;
    }

    public function getAllRoutes()
    {
        return $this->routes;
    }

    public function createCopy($form,$oldProject)
    {
        if ($form['placementMethod']==1) {
            $placementMethods = ProjectsPlacement::find()->where(['project_id'=>$oldProject])->all();
            foreach ($placementMethods as $placementMethod) {
                $new = new ProjectsPlacement();
                $new->attributes = $placementMethod->attributes;
                $new->project_id = $this->id;
                $new->save();
            }
        }
        if ($form['addresslist']==1) {
            $addresslists = ProjectAddress::find()->where(['project_id'=>$oldProject])->all();
            foreach ($addresslists as $addresslist) {
                $new = new ProjectAddress();
                $new->attributes = $addresslist->attributes;
                $new->project_id = $this->id;
                $new->save();
            }
        }
        if ($form['zones']==1) {
            $zones = Zones::find()->where(['project_id'=>$oldProject])->all();
            foreach ($zones as $zone) {
                $new = new Zones();
                $new->attributes = $zone->attributes;
                $new->project_id = $this->id;
                $new->save();
            }
        }
        if ($form['routes']==1 && $form['addresslist']==1) {
            $routes = Routes::find()->where(['project_id'=>$oldProject])->all();
            foreach ($routes as $route) {
                $new = new Routes();
                $new->attributes = $route->attributes;
                $new->project_id = $this->id;
                $new->save();
                $routeAddress = RouteAddress::find()->where(['route_id'=>$route->id])->all();
                foreach ($routeAddress as $address) {
                    $newItem = new RouteAddress();
                    $newItem->attributes = $address->attributes;
                    $newItem->route_id = $new->id;
                    $newItem->save();
                }
            }
        }
    }
}

controllers/ProjectsController.php
<?php

namespace app\controllers;

use app\models\AddressList;
use app\models\Employees;
use app\models\EmployeesMove;
use app\models\forms\ProgectCopy;
use app\models\forms\RouteAddressesForm;
use app\models\forms\UploadForm;
use app\models\ProjectAddress;
use app\models\ProjectsPlacement;
use app\models\RouteAddress;
use app\models\Routes;
use app\models\RoutesAddressList;
use app\models\RoutesAddressListSearch;
use app\models\search\ProjectAddressSearch;
use app\models\search\ProjectsPlacementSearch;
use app\models\search\RouteAddressSearch;
use app\models\search\RoutesSearch;
use app\models\search\ZonesSearch;
use app\models\Zones;
use app\services\Polygon;
use app\services\YandexStorage;
use app\source\excelReaders\ActiveRecordExcelReader;
use kartik\mpdf\Pdf;
use Yii;
use app\models\Projects;
use app\models\search\ProjectsSearch;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use \yii\web\Response;
use yii\helpers\Html;
use yii\web\UploadedFile;

/**
 * ProjectsController implements the CRUD actions for Projects model.
 */
class ProjectsController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                    'bulk-delete' => ['post'],
                ],
            ],
        ];
    }



    /**
     * Lists all Projects models.
     * @return mixed
     */
    public function actionIndex()
    {    
        $searchModel = new ProjectsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Projects model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {   
        $model = $this->findModel($id);
        $model->placements = ProjectsPlacement::find()->where(['project_id'=>$id])->asArray()->all();
        // Основная информация
        $searchModelProjectsPlacement  = new ProjectsPlacementSearch();
        $dataProviderProjectsPlacement = $searchModelProjectsPlacement->search(Yii::$app->request->queryParams);
        $dataProviderProjectsPlacement->query->andFilterWhere(['project_id'=>$id]);
        // Карта Зоны
        $searchModelZone = new ZonesSearch();
        $dataProviderZone = $searchModelZone->search(Yii::$app->request->queryParams);
        $dataProviderZone->query->andWhere(['project_id'=>$id]);

        $searchModelRoute = new RoutesSearch();
        $dataProviderRoute = $searchModelRoute->search(Yii::$app->request->queryParams);
        $dataProviderRoute->query->andWhere(['project_id'=>$id]);
        $searchModelAddress = new ProjectAddressSearch();
        $dataProviderAddress = $searchModelAddress->search(Yii::$app->request->queryParams);
        $dataProviderAddress->query->andWhere(['project_id'=>$id]);
            return $this->render('view', [
                'model' => $model,
                'searchModelProjectsPlacement' => $searchModelProjectsPlacement,
                'dataProviderProjectsPlacement' => $dataProviderProjectsPlacement,
                'searchModelZone' => $searchModelZone,
                'dataProviderZone' => $dataProviderZone,
                'searchModelRoute' => $searchModelRoute,
                'dataProviderRoute' => $dataProviderRoute,
                'searchModelAddress' => $searchModelAddress,
                'dataProviderAddress' => $dataProviderAddress,

            ]);
    }

    /**
     * Creates a new Projects model.
     * For ajax request will return json object
     * and for non-ajax request if creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $request = Yii::$app->request;
        $model = new Projects();

        if($request->isAjax){
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            if($request->isGet){
                return [
                    'title'=> "Создать новый Проект",
                    'content'=>$this->renderAjax('create', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Закрыть',['class'=>'btn btn-primary pull-left','data-dismiss'=>"modal"]).
                        Html::button('Сохранить',['class'=>'btn btn-info','type'=>"submit"])

                ];
            }else if($model->load($request->post()) && $model->save()){
                $model->maketFile = UploadedFile::getInstance($model, 'maketFile');
                $main_path = "images/maket/";
                if (!empty($model->maketFile)) {
                    if (!file_exists(($main_path))) {
                        mkdir($main_path, 0777, true);
                    }
                    $maketFile = $main_path . time() . Yii::$app->security->generateRandomString(5) . '.' . $model->maketFile->extension;
                    $model->maketFile->saveAs($maketFile);
                    $model->maket_file = '/'.$maketFile;
                    $model->save();
                }
                return [
                    'forceReload'=>'#crud-datatable-pjax',
                    'title'=> "Создать новый Проект",
                    'content'=>'<span class="text-success">Создание прошло успешно</span>',
                    'footer'=> Html::button('Закрыть',['class'=>'btn btn-primary pull-left','data-dismiss'=>"modal"]).
                        Html::a('Создать еще',['create'],['class'=>'btn btn-info','role'=>'modal-remote'])

                ];
            }else{
                return [
                    'title'=> "Создать новый Проект",
                    'content'=>$this->renderAjax('create', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Закрыть',['class'=>'btn btn-primary pull-left','data-dismiss'=>"modal"]).
                        Html::button('Сохранить',['class'=>'btn btn-info','type'=>"submit"])

                ];
            }
        }else{
            /*
            *   Process for non-ajax request
            */
            if ($model->load($request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            } else {
                return $this->render('create', [
                    'model' => $model,
                ]);
            }
        }

    }
    public function actionUpdate($id)
    {
        $request = Yii::$app->request;
        $model = $this->findModel($id);

        if($request->isAjax){
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            if($request->isGet){
                return [
                    'title'=> "Изменить проект",
                    'size'=>'modal-lg',
                    'content'=>$this->renderAjax('create', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Закрыть',['class'=>'btn btn-primary pull-left','data-dismiss'=>"modal"]).
                        Html::button('Сохранить',['class'=>'btn btn-info','type'=>"submit"])

                ];
            }else if($model->load($request->post()) && $model->save()){
                $model->maketFile = UploadedFile::getInstance($model, 'maketFile');
                $main_path = "images/maket/";
                if (!empty($model->maketFile)) {
                    if (!file_exists(($main_path))) {
                        mkdir($main_path, 0777, true);
                    }
                    $maketFile = $main_path . time() . Yii::$app->security->generateRandomString(5) . '.' . $model->maketFile->extension;
                    $model->maketFile->saveAs($maketFile);
                    $model->maket_file = '/'.$maketFile;
                    $model->save();
                }
                return [
                    'forceReload'=>'#progectMainModal',
                    'forceClose'=>true,
                ];
            }else{
                return [
                    'title'=> "Изменить проект",
                    'size'=>'modal-lg',
                    'content'=>$this->renderAjax('create', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Закрыть',['class'=>'btn btn-primary pull-left','data-dismiss'=>"modal"]).
                        Html::button('Сохранить',['class'=>'btn btn-info','type'=>"submit"])

                ];
            }
        }else{
            /*
            *   Process for non-ajax request
            */
            if ($model->load($request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            } else {
                return $this->render('create', [
                    'model' => $model,
                ]);
            }
        }

    }

    public function actionCopy($project_id)
    {
        $request = Yii::$app->request;
        $model = new Projects();
        $form = new ProgectCopy();

        if($request->isAjax){
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            if($request->isGet){
                return [
                    'title'=> "Создать новый проект",

views/projects/_form-addresslist_edit.php
<?php

use app\models\AddressList;
use app\models\Zones;
use kartik\select2\Select2;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model \app\models\RoutesAddressList */
/* @var $form yii\widgets\ActiveForm */

?>

<div class="routes-form">

    <?php $form = ActiveForm::begin(); ?>
    <div class="row">
        <div class="col-md-6"><?= $form->field($model, 'entrance')->input('number') ?></div>
        <div class="col-md-6"><?= $form->field($model, 'floor')->input('number') ?></div>
    </div>
    <div class="row">
        <div class="col-md-6"><?= $form->field($model, 'apartament')->input('number') ?></div>
        <div class="col-md-6"><?= $form->field($model, 'porter')->input('number') ?></div>
    </div>
    <div class="row">
        <div class="col-md-6"><?=$form->field($model, 'type')->dropDownList(AddressList::getTypes()) ?></div>
        <div class="col-md-6"><?= $form->field($model, 'zone_id')->dropDownList(Zones::getZoneByProject($model->project_id)) ?></div>
    </div>
    <div class="row">
        <div class="col-md-12"><?= $form->field($model, 'comment')->textarea(['rows' => 5]) ?></div>
    </div>






    <?php ActiveForm::end(); ?>

</div>

views/projects/_form-route!.php
<?php

use app\models\PlacementMethod;
use app\models\Prices;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Projects */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="projects-form">

    <?php $form = ActiveForm::begin(); ?>
    <?= $form->field($model, 'placement_id')->dropDownList(PlacementMethod::getPlacementMethodList()) ?>
    <?= $form->field($model, 'price_id')->dropDownList(Prices::getPriceListFullName()) ?>
    <?= $form->field($model, 'circulation')->textInput()?>
	<?php if (!Yii::$app->request->isAjax){ ?>
	  	<div class="form-group">
	        <?= Html::submitButton($model->isNewRecord ? 'Создать' : 'Изменить', ['class' => $model->isNewRecord ? 'btn btn-primary' : 'btn btn-info']) ?>
	    </div>
	<?php } ?>

    <?php ActiveForm::end(); ?>
</div>

views/projects/_view-main.php
<?php

use app\models\Clients;
use johnitvn\ajaxcrud\BulkButtonWidget;
use kartik\grid\GridView;
use yii\bootstrap\Modal;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $model app\models\Projects */
/* @var $form yii\widgets\ActiveForm */
?>
<style>
    #ajaxCrudModal .modal-dialog{
        width: 800px;
    }
</style>

<div class="projects-form">
    <div class="row">

        <div class="col-md-4">
            <?php Pjax::begin(['id'=>'progectMainModal'])?>
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title"> Основная информация </h3>
                </div>
                <div class="panel-body">
                    <div class="row oglavl">
                        <div class="col-md-12">
                            <span class="emp-label"><?=$model->getAttributeLabel('id')?></span>
                            <span class="emp-value"><?=$model->id?></span>
                        </div>
                    </div>
                    <div class="row oglavl">
                        <div class="col-md-12">
                            <span class="emp-label">Статус</span>
                            <span class="emp-value"><?php
                                if (strtotime($model->date_start)>time()) {
                                    echo "Планируется";
                                } elseif (strtotime($model->date_end)>time()) {
                                    echo "Текущий";
                                } else {
                                    echo "Завершенный";
                                }
                                ?></span>
                        </div>
                    </div>

                    <div class="row oglavl">
                        <div class="col-md-12">
                            <span class="emp-label"><?=$model->getAttributeLabel('name')?></span>
                            <span class="emp-value"><?=$model->name?></span>
                        </div>
                    </div>
                    <div class="row oglavl">
                        <div class="col-md-12">
                            <span class="emp-label"><?=$model->getAttributeLabel('client_id')?></span>
                            <span class="emp-value"><?=Clients::getClientList()[$model->client_id]?></span>
                        </div>
                    </div>
                    <div class="row oglavl">
                        <div class="col-md-12">
                            <span class="emp-label">Период размещения</span>
                            <span class="emp-value"><?=$model->date_start.' по '.$model->date_end?></span>
                        </div>
                    </div>
                    <div class="row oglavl">
                        <div class="col-md-12">
                            <span class="emp-label">Тираж факт</span>
                            <span class="emp-value">0</span>
                        </div>
                    </div>
                    <div class="row oglavl">
                        <div class="col-md-12">
                            <span class="emp-label">Норма на одного промоутера</span>
                            <span class="emp-value"><?=$model->normal_one?></span>
                        </div>
                    </div>
                    <div class="row oglavl">
                        <div class="col-md-12">
                            <span class="emp-label">Макет</span>
                            <span class="emp-value"><?=$model->maket?></span>
                        </div>
                    </div>
                    <div class="row oglavl">
                        <div class="col-md-12">
                            <span class="emp-label">Файл макета</span>
                            <span class="emp-value"><?=Html::a($model->maket_file,[$model->maket_file],['download'=>true,'data-pjax'=>'0','target'=>'_blank'])?></span>
                        </div>
                    </div>
                    <div class="row oglavl">
                        <div class="col-md-12">
                            <span class="emp-label">Шаблон маршрутного листа</span>
                            <span class="emp-value"><?=$model->routeTemplates->name?></span>
                        </div>
                    </div>
                    <div class="row ">
                        <div class="col-md-12">
                            <strong class="">Дополнительная информация: </strong>
                            <span ><?=$model->info_add?></span>
                        </div>
                    </div>

                </div>
            </div>
                <div class="form-group">
                    <?= Html::a('Изменить',['update','id'=>$model->id], ['class' => 'btn btn-info','role'=>'modal-remote',]) ?>
                </div>
            <?php Pjax::end()?>

        </div>


        <div class="col-md-8">
            <div id="ajaxCrudDatatable">
                <?=GridView::widget([
                    'id'=>'crud-datatable',
                    'dataProvider' => $dataProviderProjectsPlacement,
                    'filterModel' => $searchModelProjectsPlacement,
                    'pjax'=>true,
                    'columns' => require(__DIR__.'/_columnsProjectsPlacement.php'),
                    'showPageSummary' => true,
                    'toolbar'=> [
                        ['content'=>
                            '<div style="margin-top:10px;">' .
                            Html::a('Добавить <i class="glyphicon glyphicon-plus"></i>', ['placement-create','project_id'=>$model->id],
                                ['role'=>'modal-remote','title'=> 'Добавить', 'class'=>'btn btn-info']).
                            '</div>'
                        ],
                    ],
                    'striped' => true,
                    'condensed' => true,
                    'responsive' => true,
                    'panel' => [
                        'type' => 'primary',
                        'heading' => '<i class="glyphicon glyphicon-list"></i> Список цен и количества работ ',
                        'before'=>'',
                        'after'=>BulkButtonWidget::widget([
                                'buttons'=>Html::a('<i class="glyphicon glyphicon-trash"></i>&nbsp; Удалить все',
                                    ["placement-bulk-delete"] ,
                                    [
                                        "class"=>"btn btn-danger btn-xs",
                                        'role'=>'modal-remote-bulk',
                                        'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
                                        'data-request-method'=>'post',
                                        'data-confirm-title'=>'Are you sure?',
                                        'data-confirm-message'=>'Are you sure want to delete this item'
                                    ]),
                            ]).
                            '<div class="clearfix"></div>',
                    ]
                ])?>
            </div>
        </div>
    </div>
</div>
<?php Modal::begin([
    "id"=>"progectMainModal",
    "options" => [
        "tabindex" => -1,

    ],
    'size'=>'modal-lg',
    "header"=>"<h3>Основная информация</h3>",
    "footer"=>Html::button('Закрыть',['class'=>'btn btn-primary pull-left','data-dismiss'=>"modal"]).
        Html::button('Сохранить',['class'=>'btn btn-info','type'=>"submit",'onclick'=>"sendAjaxForm()"]),
])?>
<?php Modal::end(); ?>


views/projects/_view-print.php
<div class="projects-form">
    <div class="row">
        <table class="table table-bordered " style="border: 1px solid black">
            <thead>
                <tr>
                    <th colspan="2" class="text-center" style="border: 1px solid black">
                        Маршрутный лист
                    </th>
                </tr>
            </thead>
            <tr>
                <td style="border: 1px solid black">
                    №/ФИО
                </td>
                <td style="border: 1px solid black">
                    Проект: <?=$model->name?>
                </td>
            </tr>
            <tr>
                <td style="border: 1px solid black">
                    План
                </td>
                <td style="border: 1px solid black">
                    Факт
                </td>
            </tr>
            <tr>
                <td style="border: 1px solid black">
                    Зона:
                </td>

                <td style="border: 1px solid black">
                    Зоны сделаны
                </td>
            </tr>
            <tr>
                <td style="border: 1px solid black">
                    Кол-во материалов (листовок) общее: <?=$model->normal?>
                </td>
                <td rowspan="2" style="border: 1px solid black">
                    Кол-во материалов (листовок) сделанное:
                </td>
            </tr>
            <tr>
                <td style="border: 1px solid black">
                    Кол-во домов: <?=$model->count_adress?><br>
                    Кол-во квартир: <?=$model->count_apartament?>
                </td>
            </tr>
            <tr>
                <td style="border: 1px solid black">
                    Кол-во фото общее <?=$model->count_entrance*4+$model->count_adress?><br>
                    Кол-во фото адресов <?=$model->count_adress?> <br>
                    Кол-во фото подъезда (снаружи/внутри) <?=($model->count_entrance*4+$model->count_adress)-$model->count_adress?>
                </td>
                <td style="border: 1px solid black">
                    Кол-во сделанных фото всего:
                </td>
            </tr>
            <tr>
                <td rowspan="2" style="border: 1px solid black">
                    Условные обозначения: <br>
                    Кол-во сделанных листовок - поэтажная расклейка <br>
                    - не было распространения, обязательно указуем причину
                </td>
                <td style="border: 1px solid black">
                    Время начала работы:
                </td>
            </tr>
            <tr>
                <td style="border: 1px solid black">
                    Время окончания работы:
                </td>
            </tr>
            <tr>
                <td width="50%" style="border: 1px solid black">
                    <?=$project->routeTemplates->template?>
                </td>
                <td width="50%" style="border: 1px solid black">
                    <br><br>
                    ОСТАТКИ кол-во _________________ подпись ________________
                    <br><br>
                    ОСТАТКИ принял _________________ подпись ________________

                </td>
            </tr>
        </table>
    </div>
</div>

views/projects/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Projects */

?>
<div class="projects-create">
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
</div>

views/projects/create_route.php
<?php


/* @var $this yii\web\View */
/* @var $model app\models\Routes */

?>
<div class="routes-create">
    <?= $this->render('_form_route', [
        'model' => $model,
    ]) ?>
</div>